src/Loosemonkies/Bundle/CoreBundle/Entity/Phone.php
<?php

/*
 * This file is part of the LM Service project.
 *
 * (c) Loosemonkies.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Loosemonkies\Bundle\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Respect\Validation\Validator;

/**
 * @ORM\Entity(repositoryClass="Loosemonkies\Bundle\CoreBundle\Repository\PhoneRepository")
 * @ORM\Table(name="phones")
 */
class Phone
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;

    /**
     * @ORM\Column(length=150)
     */
    protected $phone_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $age;

    /**
     * @ORM\Column(length=150)
     */
    protected $name;

    /**
     * @ORM\Column(length=350)
     */
    protected $snippet;

    /**
     * @ORM\Column(length=500)
     */
    protected $description;

    /**
     * @ORM\Column(length=150)
     */
    protected $images;

    public function toArray()
    {
        $data = array(
            'id'           => $this->getId(),
            'age'          => $this->getAge(),
            'name'         => $this->getName(),
            'phone_id'     => $this->getPhoneId(),
            'snippet'      => $this->getSnippet(),
            'description'  => $this->getDescription(),
            'images'       => $this->getImages()
        );

        return $data;
    }

    public function isValid()
    {
        try {
            Validator::create()->notEmpty()->alnum()->assert($this->getAge());
            Validator::create()->notEmpty()->assert($this->getName());
            Validator::create()->notEmpty()->assert($this->getPhoneId());
        } catch (\InvalidArgumentException $e) {
            return false;
        }

        return true;
    }

    /**
     * Set age
     *
     * @param mixed $age
     *
     * @return Phone
     */
    public function setAge($age)
    {
        $this->age = $age;

        return $this;
    }

    /**
     * Get age
     *
     * @return mixed
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * Set description
     *
     * @param mixed $description
     *
     * @return Phone
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set id
     *
     * @return mixed
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get id
     *
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set images
     *
     * @param mixed $images
     *
     * @return Phone
     */
    public function setImages($images)
    {
        $this->images = $images;

        return $this;
    }

    /**
     * Get images
     *
     * @return mixed
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Set name
     *
     * @param mixed $name
     *
     * @return Phone
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set phone_id
     *
     * @param mixed $phone_id
     *
     * @return Phone
     */
    public function setPhoneId($phone_id)
    {
        $this->phone_id = $phone_id;

        return $this;
    }

    /**
     * Get phone_id
     *
     * @return mixed
     */
    public function getPhoneId()
    {
        return $this->phone_id;
    }

    /**
     * Set snippet
     *
     * @param mixed $snippet
     *
     * @return Phone
     */
    public function setSnippet($snippet)
    {
        $this->snippet = $snippet;

        return $this;
    }

    /**
     * Get snippet
     *
     * @return mixed
     */
    public function getSnippet()
    {
        return $this->snippet;
    }


}

src/Loosemonkies/Bundle/CoreBundle/Controller/DefaultController.php
<?php

namespace Loosemonkies\Bundle\CoreBundle\Controller;

use Loosemonkies\Bundle\CoreBundle\Entity\Phone;
use Loosemonkies\Bundle\CoreBundle\Repository\PhoneRepository;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends BaseController
{
    protected $data = array();

    /** @var PhoneRepository */
    protected $phoneRepository;

    public function init()
    {
        $this->response = new Response();
        $this->response->headers->set('Content-Type', 'application/json');

        $this->phoneRepository = $this->get('phone_repository');
    }

    public function indexAction($name)
    {
        return $this->render('LoosemonkiesCoreBundle:Default:index.html.twig', array('name' => $name));
    }

    public function addPhoneAction(Request $request)
    {
        $form = $this->createFormBuilder()
                     ->add('name', 'text',
                            array(
                                    'attr' => array('placeholder' => 'Enter phone name')
                                 ))
                     ->add('phone_id', 'text',
                            array(
                                'attr' => array('placeholder' => 'Enter phone id')
                            ))
                     ->add('age', 'text',
                            array(
                                'attr' => array('placeholder' => 'Enter phone age')
                            ))
                     ->add('snippet', 'text',
                            array(
                                'attr' => array('placeholder' => 'Enter phone snippet')
                            ))
                     ->add('description', 'text',
                            array(
                                'attr' => array('placeholder' => 'Enter phone description')
                            ))

                     ->add('images', 'file', array(
                        'label' => 'Images (Select single or multiple image file)',
                        'required' => false,
                        'attr' => array(
                            'accept' => 'image/*',
                            'multiple' => true
                        )))

                     ->add('Add Phone', 'submit', array('attr' => array('class' => 'btn btn-success')))
                     ->getForm();

        if ($this->getRequest()->getMethod() == 'POST') {

            $form->bind($request);

            if ($form->isValid()) {

                $formData = $form->getData();

                $imageNames = array();

                $images = $formData['images'];

                if (count($images[0]) > 0){

                    foreach($formData['images'] as $image) {

                        $imageName = $image->getClientOriginalName();

                        $image->move('upload/', $imageName);
                        $imageNames[] = $imageName;
                    }

                    $formData['images'] = implode(',', $imageNames);

                } else {
                    $formData['images'] = '';
                }

                $ret = $this->phoneRepository->insert($formData);

                if (is_array($ret)) {
                    return $this->redirect('/phone/list');

                } else {
                    return $this->redirect('/phone');
                }
            }
        }

        $formView = $form->createView();

        $formView->children['images']->vars['full_name'] = $formView->children['images']->vars['full_name'].'[]';

        $this->data['form'] = $formView;
        return $this->render('LoosemonkiesCoreBundle:Default:add.html.twig', $this->data);
    }

    public function phoneListAction()
    {
        $this->data['phones'] = $this->phoneRepository->getAll();

        return $this->render('LoosemonkiesCoreBundle:Default:list.html.twig', $this->data);
    }

    public function phoneDetailsAction($id)
    {
        $this->data['phone']  = $this->phoneRepository->getPhoneByPhoneId($id);

        return $this->render('LoosemonkiesCoreBundle:Default:details.html.twig', $this->data);
    }

    public function phoneSearchAction()
    {
        $searchDara = $this->request->request->all();

        $this->data['phones'] = $this->phoneRepository->searchPhoneByKeyword($searchDara['searchkey']);

        return $this->render('LoosemonkiesCoreBundle:Default:search.html.twig', $this->data);
    }

    public function phoneSortAction()
    {
        $searchDara = $this->request->request->all();

        $this->data['phones'] = $this->phoneRepository->searchPhoneByKeywordWithSorting($searchDara['searchkey'], $searchDara['sortkey']);

        return $this->render('LoosemonkiesCoreBundle:Default:search.html.twig', $this->data);
    }

    public function phoneEditAction($id, Request $request)
    {
        $formExistData = $this->phoneRepository->getPhoneByPhoneId($id);

        $phone = new Phone();

        $phone->setAge($formExistData['age']);
        $phone->setName($formExistData['name']);
        $phone->setSnippet($formExistData['snippet']);
        $phone->setDescription($formExistData['description']);
        $phone->setPhoneId($formExistData['phone_id']);

        $form = $this->createFormBuilder($phone)
                     ->add('name', 'text',
                        array(
                            'attr' => array('placeholder' => 'Enter phone name')
                        ))
                             ->add('phone_id', 'text',
                        array(
                            'attr' => array('placeholder' => 'Enter phone id')
                        ))
                             ->add('age', 'text',
                        array(
                            'attr' => array('placeholder' => 'Enter phone age')
                        ))
                             ->add('snippet', 'text',
                        array(
                            'attr' => array('placeholder' => 'Enter phone snippet')
                        ))
                             ->add('description', 'text',
                        array(
                            'attr' => array('placeholder' => 'Enter phone description')
                        ))

                        ->add('images', 'file', array(
                        'label' => 'Images (Select single or multiple image file)',
                        'required' => false,
                        'attr' => array(
                            'accept' => 'image/*',
                            'multiple' => true
                        )))

                     ->add('Update Phone', 'submit', array('attr' => array('class' => 'btn btn-success')))
                     ->getForm();

        if ($this->getRequest()->getMethod() == 'POST') {

            $form->bind($request);

            if ($form->isValid()) {

                $formData = $form->getData();

                $imageNames = array();

                $images = $formData->getImages();

                if (count($images[0]) > 0){

                    $existsImg = explode(',', $formExistData['images']);

                    foreach($existsImg as $unlink_img) {
                        if (file_exists('upload/'.$unlink_img)) {
                            unlink('upload/'.$unlink_img);
                        }
                    }

                    foreach($images as $image) {

                        $imageName = $image->getClientOriginalName();

                        $image->move('upload/', $imageName);
                        $imageNames[] = $imageName;
                    }

                    $img = implode(',', $imageNames);

                } else {
                    $img = null;
                }

                $newFormData['age'] = $formData->getAge();
                $newFormData['name'] = $formData->getName();
                $newFormData['phone_id'] = $formData->getPhoneId();
                $newFormData['snippet'] = $formData->getSnippet();
                $newFormData['description'] = $formData->getDescription();
                $newFormData['images'] = $img;

                $ret = $this->phoneRepository->update($formExistData['id'], $newFormData);

                if (is_array($ret)) {
                    return $this->redirect('/phone/list');

                } else {
                    return $this->redirect('/phone-edit/'.$formExistData['phone_id']);
                }
            }
        }

        $formView = $form->createView();

        $formView->children['images']->vars['full_name'] = $formView->children['images']->vars['full_name'].'[]';
        $this->data['form'] = $formView;

        $this->data['images'] = $formExistData['images'];

        return $this->render('LoosemonkiesCoreBundle:Default:edit.html.twig', $this->data);
    }

    public function phoneDeleteAction($id)
    {
        $data = $this->phoneRepository->getPhoneByPhoneId($id);

        if (empty($data)) {
            return $this->redirect('/phone/list');
        }

        $existsImg = explode(',', $data['images']);

        foreach($existsImg as $unlink_img) {
            if (file_exists('upload/'.$unlink_img)) {
                unlink('upload/'.$unlink_img);
            }
        }

        $delete = $this->phoneRepository->delete($id);

        if ($delete) {
            return $this->redirect('/phone/list');
        }

        echo 'Can not delete the phone!';
    }
}

src/Loosemonkies/Bundle/CoreBundle/Resources/views/Default/details.html.twig
{% extends 'LoosemonkiesCoreBundle::layout.html.twig' %}

{% block title %} Welcome to phone details page {% endblock %}

{% block content %}

    <div class="row-fluid" style=" margin-top: 10px !important;">

        <div class="phone-images">

            {% for key, img in images %}

                <img src="/upload/{{ id }}.{{ img }}.jpg" class="phone {% if key == 0 %} active {% endif %}">

            {% endfor %}
        </div>

        <h1>{{phone.name}}</h1>

        <p>{{phone.description}}</p>

        <ul class="phone-thumbs">
            {% for img in images %}
                <li>
                    <img src="/upload/{{ id }}.{{ img }}.jpg" onclick="setImage('{{ id }}.{{ img }}.jpg')">
                </li>
            {% endfor %}
        </ul>

    </div>

{% endblock %}

src/Loosemonkies/Bundle/CoreBundle/Resources/views/Default/edit.html.twig
{% extends 'LoosemonkiesCoreBundle::layout.html.twig' %}

{% block title %} Welcome to edit phone page {% endblock %}

{% block content %}

    <div style="float: left; padding-right: 40px;">{{ form(form) }}</div>

    <div class="row-fluid" style="margin-top: 10px !important;">
        <h1 style="margin-left: 312px;">Previously Uploaded Images</h1>
        <ul class="phone-thumbs">
            {% set classes = images|split(',') %}
            {% for img in classes|reverse %}
                <li>
                    <img src="/upload/{{ img|trim }}" />
                </li>
            {% endfor %}
        </ul>

    </div>

{% endblock %}

src/Loosemonkies/Bundle/CoreBundle/Resources/views/Default/list.html.twig
{% extends 'LoosemonkiesCoreBundle::layout.html.twig' %}

{% block title %} Welcome to phone list page {% endblock %}

{% block content %}

    <div class="row-fluid" style=" margin-top: 10px !important;">
        <div class="span2">
            <!--Sidebar content-->

            Search: <input name="query" type="text" value="" onkeyup="searchList(this.value)" class="search" />
            Sort by:
            <select name="order_prop" onchange="sortSearch(this.value)">
                <option value="name">Alphabetical</option>
                <option value="age">Newest</option>
                <option value="-age">Oldest</option>
            </select>

        </div>
        <div class="span10">
            <!--Body content-->

            <ul class="phones">
                {% for phone in phones %}
                    <li class="thumbnail phone-listing">
                        <a href="/phone-details/{{phone.phoneId}}" class="thumb">
                            {% set classes = phone.images|split(',') %}
                            {% set count = classes|length %}
                            <img src="/upload/{{classes[count-1]|trim}}">
                        </a>
                        <a href="/phone-details/{{phone.phoneId}}">{{ phone.name }}</a>

                        <p>{{phone.snippet}}</p>
                        <p>
                            <a href="/phone-edit/{{phone.phoneId}}">Edit</a> |
                            <a href="/phone-delete/{{phone.phoneId}}">Delete</a>
                        </p>
                    </li>
                {% endfor %}
            </ul>

        </div>
    </div>

{% endblock %}

src/Loosemonkies/Bundle/CoreBundle/Resources/views/Default/search.html.twig
<ul class="phones">
    {% for phone in phones %}
        <li class="thumbnail phone-listing">
            <a href="/phone-details/{{phone['phone_id']}}" class="thumb"><img src="/upload/{{phone['images']}}"></a>
            <a href="/phone-details/{{phone['phone_id']}}">{{ phone['name'] }}</a>
            <p>{{phone['snippet']}}</p>
        </li>
    {% endfor %}
</ul>